[project]
name = "pyrocketmq"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "python-statemachine>=2.5.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
